"""Added stock price table

Revision ID: 28610f9f9afc
Revises: 704055a11d69
Create Date: 2017-06-22 23:37:46.473357

"""

# revision identifiers, used by Alembic.
revision = '28610f9f9afc'
down_revision = '704055a11d69'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price',
    sa.Column('stock_price_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('opening_price', sa.Float(), nullable=True),
    sa.Column('closing_price', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('highest_price', sa.Float(), nullable=True),
    sa.Column('lowest_price', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(precision=53), nullable=True),
    sa.Column('buy_1_volume', sa.Integer(), nullable=True),
    sa.Column('buy_1_price', sa.Float(), nullable=True),
    sa.Column('buy_2_volume', sa.Integer(), nullable=True),
    sa.Column('buy_2_price', sa.Float(), nullable=True),
    sa.Column('buy_3_volume', sa.Integer(), nullable=True),
    sa.Column('buy_3_price', sa.Float(), nullable=True),
    sa.Column('buy_4_volume', sa.Integer(), nullable=True),
    sa.Column('buy_4_price', sa.Float(), nullable=True),
    sa.Column('buy_5_volume', sa.Integer(), nullable=True),
    sa.Column('buy_5_price', sa.Float(), nullable=True),
    sa.Column('sell_1_volume', sa.Integer(), nullable=True),
    sa.Column('sell_1_price', sa.Float(), nullable=True),
    sa.Column('sell_2_volume', sa.Integer(), nullable=True),
    sa.Column('sell_2_price', sa.Float(), nullable=True),
    sa.Column('sell_3_volume', sa.Integer(), nullable=True),
    sa.Column('sell_3_price', sa.Float(), nullable=True),
    sa.Column('sell_4_volume', sa.Integer(), nullable=True),
    sa.Column('sell_4_price', sa.Float(), nullable=True),
    sa.Column('sell_5_volume', sa.Integer(), nullable=True),
    sa.Column('sell_5_price', sa.Float(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_info.symbol'], ),
    sa.PrimaryKeyConstraint('stock_price_id')
    )
    op.create_index(op.f('ix_stock_price_update_datetime'), 'stock_price', ['update_datetime'], unique=False)
    op.alter_column('stock_lowest_unit', 'is_integer',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_lowest_unit', 'is_integer',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_index(op.f('ix_stock_price_update_datetime'), table_name='stock_price')
    op.drop_table('stock_price')
    ### end Alembic commands ###
