"""Added noble metal price table

Revision ID: 704055a11d69
Revises: f5d6c3692a93
Create Date: 2017-06-21 20:45:56.831678

"""

# revision identifiers, used by Alembic.
revision = '704055a11d69'
down_revision = 'f5d6c3692a93'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noble_metal_price',
    sa.Column('noble_metal_price_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('middle_price', sa.Float(), nullable=True),
    sa.Column('highest_middle_price', sa.Float(), nullable=True),
    sa.Column('lowest_middle_price', sa.Float(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_info.symbol'], ),
    sa.PrimaryKeyConstraint('noble_metal_price_id')
    )
    op.create_index(op.f('ix_noble_metal_price_update_datetime'), 'noble_metal_price', ['update_datetime'], unique=False)
    op.alter_column('stock_lowest_unit', 'is_integer',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_lowest_unit', 'is_integer',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_index(op.f('ix_noble_metal_price_update_datetime'), table_name='noble_metal_price')
    op.drop_table('noble_metal_price')
    ### end Alembic commands ###
