"""Add StockLowestGain

Revision ID: 7452158f3ef4
Revises: 43885627a611
Create Date: 2016-10-26 00:12:30.647670

"""

# revision identifiers, used by Alembic.
revision = '7452158f3ef4'
down_revision = '43885627a611'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_lowest_gain',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('lowest_gain', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_info.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_lowest_gain')
    ### end Alembic commands ###
