"""Add_all_investments_history_table

Revision ID: 7cfd15a2d7f2
Revises: b7c2e2e55b17
Create Date: 2016-12-13 21:52:45.858081

"""

# revision identifiers, used by Alembic.
revision = '7cfd15a2d7f2'
down_revision = 'b7c2e2e55b17'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_investments_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('history_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_investments_history')
    ### end Alembic commands ###
