"""add lowest unit table

Revision ID: a533a244960d
Revises: 7cfd15a2d7f2
Create Date: 2017-01-06 22:37:15.730166

"""

# revision identifiers, used by Alembic.
revision = 'a533a244960d'
down_revision = '7cfd15a2d7f2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_lowest_unit',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('lowest_unit', sa.Float(), nullable=True),
    sa.Column('is_integer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_info.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_lowest_unit')
    ### end Alembic commands ###
