"""Add total value history data table

Revision ID: b7c2e2e55b17
Revises: 7452158f3ef4
Create Date: 2016-11-16 21:13:08.966956

"""

# revision identifiers, used by Alembic.
revision = 'b7c2e2e55b17'
down_revision = '7452158f3ef4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_cash_total_history_value',
    sa.Column('history_value_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_info.symbol'], ),
    sa.PrimaryKeyConstraint('history_value_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_cash_total_history_value')
    ### end Alembic commands ###
