"""init

Revision ID: b900d3ddcf7e
Revises: 
Create Date: 2016-08-12 22:05:47.736925

"""

# revision identifiers, used by Alembic.
revision = 'b900d3ddcf7e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_info',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('stock_cash',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_info.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('stock_closed_transaction',
    sa.Column('trans_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('buy_date', sa.Date(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('sell_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_info.symbol'], ),
    sa.PrimaryKeyConstraint('trans_id')
    )
    op.create_table('stock_price_range',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_info.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('stock_transaction',
    sa.Column('trans_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('buy_or_sell', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_info.symbol'], ),
    sa.PrimaryKeyConstraint('trans_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transaction')
    op.drop_table('stock_price_range')
    op.drop_table('stock_closed_transaction')
    op.drop_table('stock_cash')
    op.drop_table('stock_info')
    ### end Alembic commands ###
