"""extend app name length

Revision ID: dfef3701086d
Revises: 28610f9f9afc
Create Date: 2017-06-24 19:20:13.713135

"""

# revision identifiers, used by Alembic.
revision = 'dfef3701086d'
down_revision = '28610f9f9afc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    op.alter_column('trade_keep_alive', 'app_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_keep_alive', 'app_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    ### end Alembic commands ###
